<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>SvnMethodLens.Core.Svn</RootNamespace>
    <AssemblyName>SvnMethodLens.Svn</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

</Project>
